### ISSUE TITLE
`Flux.Optimise.update!` no longer works on `Scheduler`

### ISSUE THREAD

**Issue by lassepe** [FluxML/ParameterSchedulers.jl#30]
Since the latest release, `Flux.Optimise.update!` no longer works on a `Scheduler` because the type of the generic optimization has been [narrowed to `AbstractOptimiser](https://github.com/FluxML/Flux.jl/compare/v0.12.10...v0.13.0#diff-0feefc760745be5d05a988b589606983887ea75bc3a7a7edab0047289e898d6aL23) in the latest release of Flux.

As an aside: it may  be worth adding some basic integration tests to this repo to test the interoperability of ParameterSchedulers with Flux.

**Comment by darsnack** [comment]
> it may be worth adding some basic integration tests

As the merging of #29 indicates...I thought these tests existed which is an oversight on my part.
