### ISSUE TITLE
Remove Flux Dependency

### ISSUE THREAD

**Issue by nikopj** [FluxML/ParameterSchedulers.jl#46]
### Motivation and description

Having Flux as a dependency seems unnessesary and can cause some package version conflict headaches. 
Optimisers.jl already has a system to adjust hyperparameters (like lr) via `Optimisers.adjust!` (see https://fluxml.ai/Optimisers.jl/dev/api/#Optimisers.adjust!). Can we remove the dependency and associated functions in favor of telling people to just use `adjust!`?

### Possible Implementation

For example, the following works:
```julia 
model = ... # init a Flux or Lux model
opt = Adam(lr)
sched = Step(lr, 0.95, step)
st_opt = Optimisers.setup(opt, model)

for ep in 1:epochs
    Optimisers.adjust!(st_opt, sched(ep))
    # loop through data, apply gradients, update params, etc
    ...
end
```

### Alternatively
Flux could be moved to a weak dependency and the Scheduler code could be moved to an extension.

**Comment by darsnack** [comment]
The next (imminent) release of Flux will drop the old style optimizers so we would drop this code anyways. No need to introduce an extension for something that will be gone soon.

**Comment by nikopj** [comment]
ok! good to know.
