### ISSUE TITLE
Remove Flux Dependency 

### ISSUE THREAD

**Issue by maximilian-gelbrecht** [FluxML/ParameterSchedulers.jl#52]
The package can be used for all kinds of ML libraries not only Flux. I use it with Lux for example as well. However, it has Flux.jl as a dependency that it will always install. From a quick look over the code the dependency on Flux is only relevant for the `Schedulers` struct. 

If the dependency there is really necessary, one could rewrite this as an extension module that is only loaded when Flux is loaded as well.

**Comment by maximilian-gelbrecht** [comment]
> If the dependency there is really necessary, one could rewrite this as an extension module that is only loaded when Flux is loaded as well.

I could make a PR for this, but this would also make Julia 1.9 a requirement. What do you think?

**Comment by darsnack** [comment]
That would be greatly appreciated. Go for it!
