### ISSUE TITLE
Links broken in documentation

### ISSUE THREAD

**Issue by BioTurboNick** [FluxML/ParameterSchedulers.jl#64]
https://fluxml.ai/ParameterSchedulers.jl/stable/

All of the links to methods in the "Available Schedules" section 404.

**Comment by adarshpalaskar1** [comment]
Hello, can I work on this issue?

I think updating the links in the README.md file will also update the docs as Documenter.jl reads it directly for the home page.

**Comment by ToucheSir** [comment]
The rule of thumb for working on an issue like this is that no permission is required :). A tested PR is more than enough.

**Comment by adarshpalaskar1** [comment]
> The rule of thumb for working on an issue like this is that no permission is required :). A tested PR is more than enough.

Sorry for that, I will test and commit the PR.
