### ISSUE TITLE
Docstring of `CosAnneal` incorrect?

### ISSUE THREAD

**Issue by dpaetzel** [FluxML/ParameterSchedulers.jl#67]
Hi! Thank you for developing and maintaining this library!

I just noticed that the [docstring of `CosAnneal`](https://github.com/FluxML/ParameterSchedulers.jl/blob/22742e1e3c955c783fb512ea4e92a1a2e2065443/src/cyclic.jl#L189) may be incorrect? Shouldn't it be

```
t̂ = restart ? mod(t - 1, period) : (t - 1)
```

instead of

```
t̂ = restart ? (t - 1) : mod(t - 1, period)
```

since the latter does not conform to [the code](https://github.com/FluxML/ParameterSchedulers.jl/blob/b3edfa8f35224b464e4c4a010271f7cc62d442b5/src/cyclic.jl#L219) whereas the former does?

**Comment by darsnack** [comment]
That's correct, thanks for catching the mistake! If you have time to file a PR, then that would be appreciated.
